language: python

dist: xenial

python:
  - "3.6"
  - "3.7"
  - "3.8"

cache:
  pip: true

before_install:
  - pip install -U pip

install:
  - pip install coveralls tox-travis

script: tox

after_script:
  - coveralls
