site_name: belvo-python
site_description: Bank connectivity simplified.

theme:
    name: 'material'

repo_name: belvo-finance/belvo-python
repo_url: https://github.com/belvo-finance/belvo-python
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Sessions: 'sessions.md'
    - Resources: 'resources.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.emoji:
